### PR TITLE
Encode formDefinition with jsonString context

### PR DESCRIPTION
**Pull request by TalmizAhmed**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by TalmizAhmed** [comment]
Support for jsonString context is now available in public AEM cloud release Release 16357

**Comment by rismehta** [comment]
> Support for jsonString context is now available in public AEM cloud release Release 16357
cc: @rismehta

What is the behavior of the code if context is not available ? Is the rendering blocked

**Comment by TalmizAhmed** [comment]
@rismehta No the rendering would just be in the default context of the html tag, without the encoding provided by jsonString

**Comment by TalmizAhmed** [comment]
@rismehta [This test case](https://github.com/adobe/aem-core-forms-components/blob/master/ui.tests/test-module/specs/page/pagev2.runtime.spec.js) will be improved by @deepprakash345 to include checks for this use case too and is being tracked by a separate ticket (FORMS-14628)

**Review by rismehta — CHANGES_REQUESTED** [review]
please add test case

**Review by rismehta — APPROVED** [review]

**Pull request merged**
