### PR TITLE
FORMS-12150 adding NP checks to avoid failures when dialog doesn't co…

### PR DESCRIPTION
**Pull request by vdua**
…ntain certain fields

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Review by sakshi-arora1 — APPROVED** [review]

**Comment by rismehta** [comment]
@vdua Could you add test case for this scenario, so that we don't miss any relevant changes in future ?

**Review by rismehta — CHANGES_REQUESTED** [review]
check comments

**Comment by rismehta** [comment]
Please create a PR on dev.

**Comment by rismehta** [comment]
Closing, created new PR. https://github.com/adobe/aem-core-forms-components/pull/1027

**Pull request closed without merging**
