### PR TITLE
FORMS-3345 Fix ID missmatch between model and view when rendered in AEM Forms container in sites.

### PR DESCRIPTION
**Pull request by ravise5**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by ravise5** [comment]
Since we are rendering the page inside the iframe the headers and footers are also visible. This is a limitation of this approach. 
cc: @nit23uec

**Comment by rismehta** [comment]
As discussed offline, this approach does not look right. Rather we should try to improve the getId logic

**Review by rismehta — CHANGES_REQUESTED** [review]
-1 for now

**Comment by ravise5** [comment]
Closing this as no longer relevant

**Pull request closed without merging**
