### PR TITLE
@trivial Changing component groups

### PR DESCRIPTION
**Pull request by rismehta**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by nit23uec** [comment]
how are you ensuring the working of sites editor ITs as currently they work on the assumption that a particular group is allowed in the sites page.

**Comment by rismehta** [comment]
> 



> how are you ensuring the working of sites editor ITs as currently they work on the assumption that a particular group is allowed in the sites page.

 via, https://github.com/adobe/aem-core-forms-components/pull/278/commits/341b4db7fa5b9d73dfc0f323672b6ea875354513. We need to keep the filters same

**Comment by nit23uec** [comment]
> > 
> 
> > how are you ensuring the working of sites editor ITs as currently they work on the assumption that a particular group is allowed in the sites page.
> 
> via, [341b4db](https://github.com/adobe/aem-core-forms-components/commit/341b4db7fa5b9d73dfc0f323672b6ea875354513). We need to keep the filters same

I wont recommend this as this is error prone and bound to brake. we are relying too much on the internals of wcm test collateral. if wcm decides  to update policy then the node name may get updates and our tests would break.

**Review by nit23uec — CHANGES_REQUESTED** [review]
the ideal way is to update wcm components policy with our grp:` Core Components Examples - Adaptive Form` . the current approach is error prone.

**Comment by rismehta** [comment]
> the ideal way is to update wcm components policy with our grp: Core Components Examples - Adaptive Form . the current approach is error prone.

This was already discussed with Vlad. We already do that today for forms and communications portal

**Review by barshat7 — APPROVED** [review]

**Pull request merged**
