### PR TITLE
Update forms structure

### PR DESCRIPTION
**Pull request by virresh**
This is accompanying changes to sites core wcm examples
See PR https://github.com/adobe/aem-core-wcm-components/pull/1862

This PR should not be merged until the other commit makes it to the master branch.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by rismehta** [comment]
@virresh The deploy to components library GH action is failing. This action was created to check usage of forms component library inside wcm component library. Can you fix the GH action before we merge this PR ?

**Comment by virresh** [comment]
Yes, had a look at the action, seems like the credentials are no longer working.

**Comment by rismehta** [comment]
> Yes, had a look at the action, seems like the credentials are no longer working.

@vladbailescu created the action. you should probably check this with him

**Comment by vladbailescu** [comment]
Updated the relevant secrets and the action goes through.

**Pull request merged**
