### PR TITLE
FORMS-13392 Role main check

### PR DESCRIPTION
**Pull request by rajatofficial**
JIRA for the test Cases: https://jira.corp.adobe.com/browse/FORMS-13508

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Review by sakshi-arora1 — COMMENTED** [review]
You will also need to honour this in core component container (guidecontainer) component.

**Comment by rismehta** [comment]
> You will also need to honour this in core component container (guidecontainer) component.

The role="main" attribute is typically used for the main content area of a web page, not specifically for form. Why did we add this in container ? Ideally, it should not be present.

**Comment by sakshi-arora1** [comment]
> > You will also need to honour this in core component container (guidecontainer) component.
> 
> The role="main" attribute is typically used for the main content area of a web page, not specifically for form. Why did we add this in container ? Ideally, it should not be present.

This is as per customer reported accessibility issue https://jira.corp.adobe.com/browse/NPR-32310

**Comment by rismehta** [comment]
@sakshi-arora1, kindly refrain from mentioning internal JIRA IDs here. The issue you provided pertains to a page rather than a form. Ideally, the attribute should be included in the page component, as mentioned previously. This attribute is specifically utilized for the main content area and not for the HTML elements of the form.

**Comment by sakshi-arora1** [comment]
> @sakshi-arora1, kindly refrain from mentioning internal JIRA IDs here. The issue you provided pertains to a page rather than a form. Ideally, the attribute should be included in the page component, as mentioned previously. This attribute is specifically utilized for the main content area and not for the HTML elements of the form.

For a standalone form and for form embedded (within iframe), form is the main content of the page, hence role main needs to be added to the container. For form embedded within a div on sites page, role main will not apply. So the fix is to conditionally add. role main.

**Comment by rismehta** [comment]
> For a standalone form and for form embedded (within iframe), form is the main content of the page, hence role main needs to be added to the container.

I acknowledge the point, but the responsibility of including role="main" in the HTML should lie with the page component rather than the form container. Otherwise, resorting to workarounds like removeRoleMain introduces complexity to the API surface and compromises code readability.

**Comment by sakshi-arora1** [comment]
> > For a standalone form and for form embedded (within iframe), form is the main content of the page, hence role main needs to be added to the container.
> 
> I acknowledge the point, but the responsibility of including role="main" in the HTML should lie with the page component rather than the form container. Otherwise, resorting to workarounds like removeRoleMain introduces complexity to the API surface and compromises code readability.

Page component will not get an opportunity to add role main. Also this is reported in our accessibility report under "Best Practice" -> landmark-one-main

**Comment by rismehta** [comment]
> > > For a standalone form and for form embedded (within iframe), form is the main content of the page, hence role main needs to be added to the container.
> > 
> > 
> > I acknowledge the point, but the responsibility of including role="main" in the HTML should lie with the page component rather than the form container. Otherwise, resorting to workarounds like removeRoleMain introduces complexity to the API surface and compromises code readability.
> 
> Page component will not get an opportunity to add role main. Also this is reported in our accessibility report under "Best Practice" -> landmark-one-main

> Page component will not get an opportunity to add role main.
Could you clarify your statement about the page component not getting an opportunity? While I acknowledge that this is an accessibility issue, I believe the proposed solution for addressing the problem is not accurate.

**Comment by rismehta** [comment]
merging this since the change

> > > For a standalone form and for form embedded (within iframe), form is the main content of the page, hence role main needs to be added to the container.
> > 
> > 
> > I acknowledge the point, but the responsibility of including role="main" in the HTML should lie with the page component rather than the form container. Otherwise, resorting to workarounds like removeRoleMain introduces complexity to the API surface and compromises code readability.
> 
> Page component will not get an opportunity to add role main. Also this is reported in our accessibility report under "Best Practice" -> landmark-one-main

For reference, HTML spec, https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element

ideally this is how the HTML structure should be
```
 <!-- Page Component -->
<html>
   <head>
   </head
   <body>
      <!-- Header Component -->
      <header>
          <!-- Header content goes here -->
      </header>

      <!-- Main Content Area with role="main" --> // we might need some hook to inject this when the page is just containing the entire form
      <main role="main">
          <!-- Other components/content on the page -->
  
          <!-- Adaptive Form Inclusion -->
  
          <!-- Other components/content on the page -->
      </main>

    <!-- Footer Component -->
    <footer>
        <!-- Footer content goes here -->
    </footer>
</div>
```

**Comment by sakshi-arora1** [comment]
@rismehta still not merged

> merging this since the change
> 
> > > > For a standalone form and for form embedded (within iframe), form is the main content of the page, hence role main needs to be added to the container.
> > > 
> > > 
> > > I acknowledge the point, but the responsibility of including role="main" in the HTML should lie with the page component rather than the form container. Otherwise, resorting to workarounds like removeRoleMain introduces complexity to the API surface and compromises code readability.
> > 
> > 
> > Page component will not get an opportunity to add role main. Also this is reported in our accessibility report under "Best Practice" -> landmark-one-main
> 
> For reference, HTML spec, https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element
> 
> ideally this is how the HTML structure should be
> 
> ```
>  
> <html>
>    <head>
>    </head
>    <body>
>       
>       <header>
>           
>       </header>
> 
>        // we might need some hook to inject this when the page is just containing the entire form
>       <main role="main">
>           
>   
>           
>   
>           
>       </main>
> 
>     
>     <footer>
>         
>     </footer>
> </div>
> ```

@rismehta still not merged

**Pull request merged**
