### PR TITLE
FORMS-14580 | Retiring FT-FORMS-8771

### PR DESCRIPTION
**Pull request by navneet-ag**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Review by rismehta — CHANGES_REQUESTED** [review]
Can you remove this from the static toggle provider configuration ?

**Comment by navneet-ag** [comment]
> Can you remove FT from the static toggle provider configuration ?

@rismehta I could not find the usage of this FT anywhere else in the repo.
I also checked https://github.com/adobe/aem-core-forms-components/blob/master/it/config/src/main/content/jcr_root/apps/system/config/com.adobe.granite.toggle.impl.dev.DynamicToggleProviderImpl.cfg.json could not find the usage here.

Is static toggle provider configuration listed somewhere else ?

**Comment by rismehta** [comment]
> Is static toggle provider configuration listed somewhere else ?

Was this FT enabled as part of the product itself ?

**Comment by navneet-ag** [comment]
Yes this FT was enabled as a part of product as is already GA.

**Review by rismehta — APPROVED** [review]

**Pull request merged**
