### PR TITLE
CQ-4348928 - AF2 Template and Template-Type Structure Layer and policy changes

### PR DESCRIPTION
**Pull request by pankaj-parashar**
## Description

- To show templates types from /libs/settings/wcm/template-types in addition to template-types defined in the project folder
- Defining separate policies for header and footer allowing the required component only

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Review by nit23uec — APPROVED** [review]

**Comment by sakshi-arora1** [comment]
@pankaj-parashar / @nit23uec There was also a task to make responsive default for panel via content policy, is that being tracked seperately.

**Comment by pankaj-parashar** [comment]
> default

@sakshi-arora1 , I am not aware of this. This PR is for items listed in issue CQ-4348928.

**Comment by pankaj-parashar** [comment]
> > @pankaj-parashar / @nit23uec There was also a task to make responsive default for panel via content policy, is that being tracked separately?
> 
> @sakshi-arora1 , I am not aware of this. This PR is for items listed in issue CQ-4348928.

@sakshi-arora1 , Added this policy via commit https://github.com/adobe/aem-core-forms-components/pull/290/commits/d7e5401c5473950d1d8be85886e08854de14e62f. Please review the same.

**Review by sakshi-arora1 — APPROVED** [review]

**Comment by nit23uec** [comment]
Let's remove the panel container policy change from this PR. it should be dealt with separately as the change is not trivial as previously thought. This would avoid the workaround of having 2 templates that is not desirable.

**Comment by pankaj-parashar** [comment]
> Let's remove the panel container policy change from this PR. it should be dealt with separately as the change is not trivial as previously thought. This would avoid the workaround of having 2 templates that is not desirable.

Done

**Pull request merged**
