### PR TITLE
[CQ-4351856] Check syncing of HTML for each core component in repeatability.

### PR DESCRIPTION
**Pull request by TalmizAhmed**
## Description
Tests for repeatability for each core component and make sure none of the Id's are duplicated. Currently excluding the ones that have a bug in them (Radiobtn, checkbox, fileinput). 

## Related Issue
[CQ-4351856](https://jira.corp.adobe.com/browse/CQ-4351856)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by TalmizAhmed** [comment]
Closing the PR since additional changes are needed.

**Comment by nit23uec** [comment]
is this required now after https://github.com/adobe/aem-core-forms-components/pull/471 ?

**Comment by TalmizAhmed** [comment]
@nit23uec Looks like @deepprakash345 pulled in the code from this branch in his PR.

**Comment by TalmizAhmed** [comment]
Merged in https://github.com/adobe/aem-core-forms-components/pull/471

**Pull request closed without merging**
